add modes
shhhwepsss/smart-greenhouse pull request #9
Opened 2022-05-19 23:04 UTC by shhhwepsss

2022-05-22 09:14 UTC, martinLjs requested changes

2022-05-22 09:14 UTC, martinLjs commented on src/components/ModaleWindow/Settings/Servo/Servo.tsx
> +      case "timer":
это в enum надо

enum settings {
TIMER = 'timer',
TIMERRTC = 'timerrtc',
}
например

2022-05-22 09:14 UTC, martinLjs commented on src/components/ModaleWindow/Settings/Servo/Servo.tsx
> +            {settindsIsOpen ? showSettings(selectData) : <></>}
пустой фрагмент? а null не подойдет?

2022-05-22 09:14 UTC, martinLjs commented on src/components/ModaleWindow/Settings/Rele/Rele.tsx
> +  const showSettings = (selectData: string) => {
эта функция дублируется в двух местах минимум, похоже надо вынести её

2022-05-22 09:14 UTC, martinLjs commented on src/components/ModaleWindow/Settings/Rele/Rele.tsx
>    windowIsOpen: Boolean;
boolean*

не Function, а () => void лучше(void и параметры уже сами типизируйте, это пример)

2022-05-22 09:14 UTC, martinLjs commented on src/components/ModaleWindow/Settings/Rele/Rele.tsx
> +  const [selectData, setSelectData] = useState<string>("Timer");
почему тут Timer, а внизу timer?

это должны быть значения enum

2022-05-22 09:14 UTC, martinLjs commented on src/components/Modes/SensorMode/SensorMode.tsx
> +    setSettingsIsOpen: Function
см выше

2022-05-22 09:14 UTC, martinLjs commented on src/components/Modes/TimerRTC/TimerRTC.tsx
> +    setSettingsIsOpen: Function
см выше

2022-05-22 09:14 UTC, martinLjs commented on src/components/Modes/TimerRTC/TimerRTC.tsx
> +export const TimerRTC: React.FC<TimerRTCProps> = ({setSettingsIsOpen}) => {
не используется prettier  ({setSettingsIsOpen})

2022-05-22 09:14 UTC, martinLjs commented on src/components/Modes/Week/Week.tsx
> +    const selectWeek = (e:SyntheticEvent ) => {
...Event ) **: void** => { ...

2022-05-22 21:45 UTC, shhhwepsss commented on src/components/Modes/Week/Week.tsx
> +    const selectWeek = (e:SyntheticEvent ) => {
```suggestion
    const selectWeek = (e:SyntheticEvent ) => {
```
const selectWeek = (e:SyntheticEvent ):void => {

2022-05-22 21:47 UTC, shhhwepsss commented on src/components/Modes/Week/Week.tsx
> +    const selectWeek = (e:SyntheticEvent ) => {
```suggestion
    const selectWeek = (e:SyntheticEvent ):void => {
```
Обязательно указывать тип возвращаемого значения? Он же по умолчанию void

2022-05-31 19:55 UTC, shhhwepsss commented on src/components/ModaleWindow/Settings/Servo/Servo.tsx
> +            {settindsIsOpen ? showSettings(selectData) : <></>}
возвращать null в дом дерево страшно

2022-05-31 20:06 UTC, shhhwepsss commented on src/components/ModaleWindow/Settings/Rele/Rele.tsx
>    windowIsOpen: Boolean;
пока Function оставлю. Нужно ts глубже мне изучить

2022-05-31 20:08 UTC, merged